/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type InstrumentType = 'Stock' | 'Currency' | 'Bond' | 'Etf';

export const InstrumentType = {
    Stock: 'Stock' as InstrumentType,
    Currency: 'Currency' as InstrumentType,
    Bond: 'Bond' as InstrumentType,
    Etf: 'Etf' as InstrumentType
};