/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type OperationTypeWithCommission = 'Buy' | 'BuyCard' | 'Sell' | 'BrokerCommission' | 'ExchangeCommission' | 'ServiceCommission' | 'MarginCommission' | 'OtherCommission' | 'PayIn' | 'PayOut' | 'Tax' | 'TaxLucre' | 'TaxDividend' | 'TaxCoupon' | 'TaxBack' | 'Repayment' | 'PartRepayment' | 'Coupon' | 'Dividend' | 'SecurityIn' | 'SecurityOut';

export const OperationTypeWithCommission = {
    Buy: 'Buy' as OperationTypeWithCommission,
    BuyCard: 'BuyCard' as OperationTypeWithCommission,
    Sell: 'Sell' as OperationTypeWithCommission,
    BrokerCommission: 'BrokerCommission' as OperationTypeWithCommission,
    ExchangeCommission: 'ExchangeCommission' as OperationTypeWithCommission,
    ServiceCommission: 'ServiceCommission' as OperationTypeWithCommission,
    MarginCommission: 'MarginCommission' as OperationTypeWithCommission,
    OtherCommission: 'OtherCommission' as OperationTypeWithCommission,
    PayIn: 'PayIn' as OperationTypeWithCommission,
    PayOut: 'PayOut' as OperationTypeWithCommission,
    Tax: 'Tax' as OperationTypeWithCommission,
    TaxLucre: 'TaxLucre' as OperationTypeWithCommission,
    TaxDividend: 'TaxDividend' as OperationTypeWithCommission,
    TaxCoupon: 'TaxCoupon' as OperationTypeWithCommission,
    TaxBack: 'TaxBack' as OperationTypeWithCommission,
    Repayment: 'Repayment' as OperationTypeWithCommission,
    PartRepayment: 'PartRepayment' as OperationTypeWithCommission,
    Coupon: 'Coupon' as OperationTypeWithCommission,
    Dividend: 'Dividend' as OperationTypeWithCommission,
    SecurityIn: 'SecurityIn' as OperationTypeWithCommission,
    SecurityOut: 'SecurityOut' as OperationTypeWithCommission
};