/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';
import { InstrumentType } from './instrumentType';
import { MoneyAmount } from './moneyAmount';
import { OperationStatus } from './operationStatus';
import { OperationTrade } from './operationTrade';
import { OperationTypeWithCommission } from './operationTypeWithCommission';

export interface Operation { 
    id: string;
    status: OperationStatus;
    trades?: Array<OperationTrade>;
    commission?: MoneyAmount;
    currency: Currency;
    payment: number;
    price?: number;
    /**
     * Число инструментов в выставленной заявке
     */
    quantity?: number;
    /**
     * Число инструментов, исполненных в заявке
     */
    quantityExecuted?: number;
    figi?: string;
    instrumentType?: InstrumentType;
    isMarginCall: boolean;
    /**
     * ISO8601
     */
    date: Date;
    operationType?: OperationTypeWithCommission;
}