/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Статус заявки
 */
export type OrderStatus = 'New' | 'PartiallyFill' | 'Fill' | 'Cancelled' | 'Replaced' | 'PendingCancel' | 'Rejected' | 'PendingReplace' | 'PendingNew';

export const OrderStatus = {
    New: 'New' as OrderStatus,
    PartiallyFill: 'PartiallyFill' as OrderStatus,
    Fill: 'Fill' as OrderStatus,
    Cancelled: 'Cancelled' as OrderStatus,
    Replaced: 'Replaced' as OrderStatus,
    PendingCancel: 'PendingCancel' as OrderStatus,
    Rejected: 'Rejected' as OrderStatus,
    PendingReplace: 'PendingReplace' as OrderStatus,
    PendingNew: 'PendingNew' as OrderStatus
};