/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrderResponse } from './orderResponse';
import { TradeStatus } from './tradeStatus';

export interface Orderbook { 
    figi: string;
    depth: number;
    bids: Array<OrderResponse>;
    asks: Array<OrderResponse>;
    tradeStatus: TradeStatus;
    /**
     * Шаг цены
     */
    minPriceIncrement: number;
    /**
     * Номинал для облигаций
     */
    faceValue?: number;
    lastPrice?: number;
    closePrice?: number;
    /**
     * Верхняя граница цены
     */
    limitUp?: number;
    /**
     * Нижняя граница цены
     */
    limitDown?: number;
}