/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type SandboxCurrency = 'RUB' | 'USD' | 'EUR' | 'GBP' | 'HKD' | 'CHF' | 'JPY' | 'CNY' | 'TRY';

export const SandboxCurrency = {
    RUB: 'RUB' as SandboxCurrency,
    USD: 'USD' as SandboxCurrency,
    EUR: 'EUR' as SandboxCurrency,
    GBP: 'GBP' as SandboxCurrency,
    HKD: 'HKD' as SandboxCurrency,
    CHF: 'CHF' as SandboxCurrency,
    JPY: 'JPY' as SandboxCurrency,
    CNY: 'CNY' as SandboxCurrency,
    TRY: 'TRY' as SandboxCurrency
};