// Generated by https://quicktype.io

export interface IntradayData {
  pagination: Pagination;
  data:       Datum[];
}

export interface Datum {
  open:     number;
  high:     number;
  low:      number;
  last:     number;
  close:    number;
  volume:   number;
  date:     string;
  symbol:   Symbol;
  exchange: Exchange;
}

export enum Exchange {
  Iexg = "IEXG",
}

export enum Symbol {
  Aapl = "AAPL",
}

export interface Pagination {
  limit:  number;
  offset: number;
  count:  number;
  total:  number;
}
